"""Model lifecycle and inference - onnxruntime backend, numpy preprocessing.

Loaded at module level during Lambda init so warm invocations reuse the
session and its optimized execution plan. No torch, no torchvision - the
entire inference path is 3 packages: onnxruntime, numpy, pillow.

Preprocessing mirrors torchvision's `Resize -> ToTensor -> Normalize` in
raw numpy so tests/golden_probs.json parity check (generated by
tools/export_onnx.py) holds to within 1e-3.
"""
from __future__ import annotations

import io
import time
from typing import TypedDict

import numpy as np
import onnxruntime as ort
from PIL import Image, UnidentifiedImageError

from config import MODEL_INPUT_SIZE, MODEL_PATH, logger
from labels import CLASS_NAMES, display_name

# --- ImageNet normalization constants (matches torchvision preset) ---
_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)


class PredictionResult(TypedDict):
    raw_class: str
    confidence_score: float
    all_scores: dict[str, float]  # display_name -> probability


# --- Module-level init (runs once per cold start) ---
logger.info(f"[INIT] loading ONNX session path={MODEL_PATH}")
_init_start = time.monotonic()

_session_options = ort.SessionOptions()
_session_options.intra_op_num_threads = 1  # analog to torch.set_num_threads(1)
_session_options.inter_op_num_threads = 1
_session_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

_SESSION = ort.InferenceSession(
    MODEL_PATH,
    sess_options=_session_options,
    providers=["CPUExecutionProvider"],
)

_init_ms = int((time.monotonic() - _init_start) * 1000)
_input_name = _SESSION.get_inputs()[0].name
_output_name = _SESSION.get_outputs()[0].name
logger.info(
    f"[INIT] session ready in {_init_ms}ms "
    f"input={_input_name} output={_output_name} classes={len(CLASS_NAMES)}"
)

# Drift sanity check: classifier output dimension must match labels
_output_shape = _SESSION.get_outputs()[0].shape
if isinstance(_output_shape[-1], int) and _output_shape[-1] != len(CLASS_NAMES):
    raise RuntimeError(
        f"[INIT] class drift: ONNX output has {_output_shape[-1]} classes "
        f"but CLASS_NAMES has {len(CLASS_NAMES)}"
    )


class ImageDecodeError(ValueError):
    """Raised when the raw image bytes cannot be decoded by PIL."""


def _preprocess(image_bytes: bytes) -> np.ndarray:
    """Decode JPEG, resize, normalize, transpose to NCHW float32.

    Equivalent to torchvision's:
        Compose([Resize((256,256)), ToTensor(), Normalize(imagenet_mean, imagenet_std)])

    Bit-wise parity verified by tools/export_onnx.py against the torch+torchvision
    pipeline at tolerance 1e-3.
    """
    try:
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except (UnidentifiedImageError, OSError) as exc:
        raise ImageDecodeError(
            f"Goruntu dosyasi okunamadi: {type(exc).__name__}"
        ) from exc

    image = image.resize(MODEL_INPUT_SIZE, Image.BILINEAR)
    arr = np.asarray(image, dtype=np.float32) / 255.0
    arr = (arr - _MEAN) / _STD
    arr = arr.transpose(2, 0, 1)  # HWC -> CHW
    return np.expand_dims(arr, axis=0)  # batch dim


def _softmax(logits: np.ndarray) -> np.ndarray:
    """Numerically-stable softmax over the last axis."""
    shifted = logits - logits.max(axis=-1, keepdims=True)
    exp = np.exp(shifted)
    return exp / exp.sum(axis=-1, keepdims=True)


def predict(image_bytes: bytes) -> PredictionResult:
    """Run inference on raw image bytes.

    Raises ImageDecodeError if the bytes cannot be decoded. Any other
    exception bubbles up as an internal 500 in the handler.
    """
    tensor = _preprocess(image_bytes)
    logits = _SESSION.run([_output_name], {_input_name: tensor})[0]
    probs = _softmax(logits)[0]  # drop batch dim

    class_idx = int(np.argmax(probs))
    raw_class = CLASS_NAMES[class_idx]
    confidence = float(probs[class_idx])

    all_scores = {
        display_name(CLASS_NAMES[i]): round(float(probs[i]), 6)
        for i in range(len(CLASS_NAMES))
    }

    return {
        "raw_class": raw_class,
        "confidence_score": confidence,
        "all_scores": all_scores,
    }
